CREATE TABLE IF NOT EXISTS fics (
    id TEXT PRIMARY KEY,
    title TEXT,
    author TEXT,
    link TEXT,
    summary TEXT,
    rating TEXT,
    category TEXT,
    status TEXT,
    is_translated INTEGER,
    words INTEGER,
    chapters INTEGER,
    kudos INTEGER,
    hits INTEGER,
    comments INTEGER,
    bookmarks INTEGER,
    tags_json TEXT,
    quote TEXT,
    base_spice INTEGER,
    base_angst INTEGER,
    base_fluff INTEGER,
    base_plot INTEGER,
    base_romance INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
